version: '3.9'

name: musbookingtest

services:

  db:
    image: postgres
    restart: always
    hostname: postgreshost
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - redis-network 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - redis-network 

  redis:
    image: redis:latest
    restart: always
    hostname: redishost
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    networks:
      - redis-network
    depends_on:
      - redis

  musbooking:
    image: musbooking-api
    restart: always
    hostname: musbookinghost
    ports:
      - 9999:8080
    networks:
      - redis-network 

volumes:
  redis:
  redis-config:

networks:
  redis-network:
    driver: bridge